### ISSUE TITLE
Incorrect target output from mapper in pattern case

### ISSUE THREAD

**Issue by der** [epimorphics/github-actions#5]
With a `deployment.yaml` such as:

```
name:  epimorphics/nrw-bwq-profiles
deployments:
  - prod:
      tag: "{ver}"
  - dev:
      branch: dev
```

Tag the repo as e.g. `1.1.1`. In the current mapper implementation the mapper will return a target of `1.1.1` instead of `prod` which, when used with the ansible deployment, will mean `1.1.1` is used as the `stage` (i.e. environment).
